# Generated by Django 2.2.9 on 2020-01-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobook', '0002_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobook',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photobook',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
